### ISSUE TITLE
Is it possible to import a multi-page pdf file into separate images instead of separate layers?

### ISSUE THREAD

**Issue by hidp123** [otuncelli/Portable-Document-Format-Plugin-for-Paint.NET#1]
Hi, is it possible to import a multi-page pdf file into separate images instead of separate layers?

**Comment by otuncelli** [comment]
No. Paint.NET doesn't allow that.

There is a workaround though.
You can use `Zip Archive FileType Plugin` to export layers as zipped set of images and then extract the zip, then drag & drop the extracted images into Paint.NET.
https://forums.getpaint.net/topic/31996-zip-archive-filetype-plugin-zip-latest-v14-2021-11-04/
